esphome:
  name: garage-cam
  platform: ESP32
  board: esp-wrover-kit

wifi:
  ssid: "homenet"
  password: "smallwhitedog"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Garage-Cam Fallback Hotspot"
    password: "kTAaAykwgA0E"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

esp32_camera:
  name: My Camera
  external_clock:
    pin: GPIO32
    frequency: 20MHz
  i2c_pins:
    sda: GPIO13
    scl: GPIO12
  data_pins: [GPIO5, GPIO14, GPIO4, GPIO15, GPIO18, GPIO23, GPIO36, GPIO39]
  vsync_pin: GPIO27
  href_pin: GPIO25
  pixel_clock_pin: GPIO19
  resolution: 800x600
  # resolution: 320x240
  vertical_flip: false
  # horizontal_mirror: true

# packages:
#     <<: !include_dir_named common
#     board: !include boards/esp32_dev.yaml
#     i2c: !include components/i2c_esp32.yaml

binary_sensor:
  # Motion sensor
  - platform: gpio
    pin: GPIO33
    name: garage-cam PIR
    device_class: motion
  # Right Button
  - platform: gpio
    pin:
      number: GPIO34
      inverted: True
    name: garage-cam Button

status_led:
  pin: 2

# esp32_camera:
#         name: ${name} Camera
#     external_clock:
#         pin: GPIO4
#     frequency: 20MHz
#     i2c_pins:
#         sda: GPIO18
#     scl: GPIO23
#     data_pins: [GPIO34, GPIO13, GPIO14, GPIO35, GPIO39, GPIO38, GPIO37, GPIO36]
#     vsync_pin: GPIO5
#     href_pin: GPIO27
#     pixel_clock_pin: GPIO25
#     # Camera resolution
#     # Demo FW max. res CIF(400x296) for face recognition
# resolution: 800x600
# jpeg_quality: 10
# vertical_flip: true
# horizontal_mirror: false

#       font:
#           - file: "fonts/times-new-roman.ttf"
#       id: tnr1
#       size: 20
#     - file: "fonts/times-new-roman.ttf"
#       id: tnr2
#       size: 35

#       display:
#           - platform: ssd1306_i2c
#       model: "SSD1306 128x64"
#       rotation: 180°
#       address: 0x3C
#       lambda: |-
#           it.strftime(64, 0, id(tnr1), TextAlign::TOP_CENTER,"%d-%m-%Y", id(time_homeassistant).now());
#           it.strftime(64, 64, id(tnr2), TextAlign::BASELINE_CENTER, "%H:%M", id(time_homeassistant).now());
